name: pocketbase_drift
description: A pocketbase client backed by drift database.\
version: 0.0.1

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  pocketbase: ^0.6.0
  drift: ^2.4.1
  sqlite3_flutter_libs: ^0.5.12
  path_provider: ^2.0.11
  path: ^1.8.2
  sqlite3: ^1.9.1
  drift_dev: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3

flutter:

flutter_scripts:
  schema: flutter pub run drift_dev schema dump lib/src/database/database.dart drift_schemas/